spring:
  application:
  name: springbasicmvn
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: changemeinprod!
  jpa:
      hibernate:
        ddl-auto: update


server:
  port: 8080

